//base image path
const baseImagePath = './public/images/fakultas/'

const prodi  = [
  //Prodi FPMIPA
    {
      name: 'Pendidikan Matematika', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendmat.jpg',
      slug: 's1-pendidikan-matematika', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Pendidikan Biologi',
      jenjang: 'S1',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5', 
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendbio.jpg',
      slug: 's1-pendidikan-biologi', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA', 
    },
    {
      name: 'Pendidikan Kimia',
      jenjang: 'S1', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkim.jpg',
      slug: 's1-pendidikan-kimia',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Pendidikan Fisika',
      jenjang: 'S1', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendfis.jpg',
      slug: 's1-pendidikan-fisika',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Pendidikan Ilmu Komputer', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkom.jpg',
      slug: 's1-pendidikan-ilmu-komputer',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Matematika', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/mat.jpg',
      slug: 's1-matematika', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Biologi', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/bio.jpg',
      slug: 's1-biologi', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA', 
    },
    {
      name: 'Kimia', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/kim.png',
      slug: 's1-kimia',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Fisika', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/fis.jpg',
      slug: 's1-fisika',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'Ilmu Komputer', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/kom.jpg',
      slug: 's1-ilmu-komputer',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },
    {
      name: 'International Program on Science Education',  
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPMIPA.jpg',
      slug: 's1-ipse',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPMIPA',
    },


    // Prodi FIP
    {
      name: 'Administrasi Pendidikan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendadmin.jpg',
      slug: 's1-administrasi-pendidikan', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FIP',
    },
    {
      name: 'Psikologi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/psi.jpg',
      slug: 's1-psikologi', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FIP', 
    },
    {
      name: 'Pendidikan Khusus',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkhus.jpg',
      slug: 's1-pendidikan-khusus',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FIP',
    },
    {
      name: 'Teknologi Pendidikan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/tekpend.jpg',
      slug: 's1-teknologi-pendidikan',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FIP',
    },
    //Prodi FPTK
    {
      name: 'Pendidikan Teknik Arsitektur',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPTK.png',
      slug: 's1-pendidikan-teknik-arsitektur', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPTK',
    },
    {
      name: 'Pendidikan Teknik Elektro',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPTK.jpg',
      slug: 's1-pendidikan-teknik-elektro', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPTK', 
    },
    {
      name: 'Arsitektur',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPTK.jpg',
      slug: 's1-arsitektur', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPTK',
    },
    {
      name: 'Teknik Elektro',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPTK.jpg',
      slug: 's1-teknik-elektro', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPTK', 
    },
    

    //Prodi FPOK
    {
      name: 'Pendidikan Kepelatihan Olahraga',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPOK.jpg',
      slug: 's1-pko', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPOK',
    },
    {
      name: 'Pendidikan Jasmani, Kesehatan dan Rekreasi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPOK.jpg',
      slug: 's1-pjkr', 
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'fok', 
    },
    {
      name: 'PGSD Pendidikan Jasmani Bumi Siliwangi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPOK.jpg',
      slug: 's1-pendidikan-jasmani',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPOK',
    },
    {
      name: 'Ilmu Keolahragaan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPOK.jpg',
      slug: 's1-ilmu-keolahragaan',
      jml_mahasiswa: 200,
      jml_dosen: 40 , 
      wkt_lulus:'4.5 Tahun',
      kerjasama:' - 2020 UN\n - 2021 UM', 
      ratio: '1: 5',
      fakultas: 'FPOK',
    },
  ]  

module.exports = prodi
