//base image path
const baseImagePath = './public/images/fakultas/'

const prodi  = [
  //Prodi FPMIPA
    {
      name: 'Pendidikan Matematika',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendmat.jpg',
      slug: 's1-pendidikan-matematika', 
      fakultas: 'fpmipa',
    },
    {
      name: 'Pendidikan Biologi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendbio.jpg',
      slug: 's1-pendidikan-biologi', 
      fakultas: 'fpmipa', 
    },
    {
      name: 'Pendidikan Kimia',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkim.jpg',
      slug: 's1-pendidikan-kimia',
      fakultas: 'fpmipa',
    },
    {
      name: 'Pendidikan Fisika',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendfis.jpgg',
      slug: 's1-pendidikan-fisika',
      fakultas: 'fpmipa',
    },
    {
      name: 'Pendidikan Ilmu Komputer',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkom.jpg',
      slug: 's1-pendidikan-ilmu-komputer',
      fakultas: 'fpmipa',
    },
    {
      name: 'Matematika',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/mat.jpg',
      slug: 's1-matematika', 
      fakultas: 'fpmipa',
    },
    {
      name: 'Biologi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/bio.jpg',
      slug: 's1-biologi', 
      fakultas: 'fpmipa', 
    },
    {
      name: 'Kimia',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/kim.png',
      slug: 's1-kimia',
      fakultas: 'fpmipa',
    },
    {
      name: 'Fisika',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/fis.jpg',
      slug: 's1-fisika',
      fakultas: 'fpmipa',
    },
    {
      name: 'Ilmu Komputer',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/kom.jpg',
      slug: 's1-ilmu-komputer',
      fakultas: 'fpmipa',
    },
    {
      name: 'International Program on Science Education',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FPMIPA.jpg',
      slug: 's1-international-program-on-science-education',
      fakultas: 'fpmipa',
    },


    // Prodi FIP
    {
      name: 'Administrasi Pendidikan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendadmin.jpg',
      slug: 's1-administrasi-pendidikan', 
      fakultas: 'fip',
    },
    {
      name: 'Psikologi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/psi.jpg',
      slug: 's1-psikologi', 
      fakultas: 'fip', 
    },
    {
      name: 'Pendidikan Khusus',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/pendkhus.jpg',
      slug: 's1-pendidikan-khusus',
      fakultas: 'fip',
    },
    {
      name: 'Teknologi Pendidikan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/tekpend.jpg',
      slug: 's1-teknologi-pendidikan',
      fakultas: 'fip',
    },
    //Prodi FPTK
    {
      name: 'Pendidikan Teknik Arsitektur',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-pendidikan-teknik-arsitektur', 
      fakultas: 'fptk',
    },
    {
      name: 'Pendidikan Teknik Elektro',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-pendidikan-teknik-elektro', 
      fakultas: 'fptk', 
    },
    {
      name: 'Arsitektur',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-arsitektur', 
      fakultas: 'fptk',
    },
    {
      name: 'Teknik Elektro',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-teknik-elektro', 
      fakultas: 'fptk', 
    },
    

    //Prodi FPOK
    {
      name: 'Pendidikan Kepelatihan Olahraga',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-pko', 
      fakultas: 'fpok',
    },
    {
      name: 'Pendidikan Jasmani, Kesehatan dan Rekreasi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-pjkr', 
      fakultas: 'fok', 
    },
    {
      name: 'PGSD Pendidikan Jasmani Bumi Siliwangi',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-pendidikan-jasmani',
      fakultas: 'fpok',
    },
    {
      name: 'Ilmu Keolahragaan',
      jenjang: 'S1',
      akreditasi: 'A',
      url_image: 'http://localhost:3000/img/FIP.png',
      slug: 's1-ilmu-keolahragaan',
      fakultas: 'fpok',
    },
  ]  

module.exports = prodi
